Alt list text fix
RDjarbeng/countdown pull request #108
Opened 2022-05-23 14:58 UTC by RDjarbeng

Show due date instead of text 'elapsed' on countdown elapsed on listpage

2022-05-23 15:15 UTC, nyakotey requested changes
I was hoping it would be of the format `Due: d-m-y` like the former
just the date `d-m-y` is a bit ambiguous

2022-05-23 20:01 UTC, RDjarbeng commented
Changes completed

2022-05-24 11:43 UTC, nyakotey approved these changes

2022-05-24 12:24 UTC, merged

2022-05-24 12:26 UTC, RDjarbeng commented
Should not have activated service worker, will comment it out on altlistpage