Fix: Today Page Not Updating #126
RDjarbeng/countdown pull request #127
Opened 2024-05-01 07:40 UTC by JohnPatrickAncajas

The issue was that the DOM elements were being updated every second, but the data they displayed was not changing because it was only being set on page load or reload. To resolve this, I modified the code so that the today variable, which holds the current date and time, is refreshed every second within the setInterval function. This ensures that the data is current when it’s used to update the DOM elements. Additionally, I consolidated the getAndSetDomElements and setDomElements functions into a single setDomElements function to streamline the code. Now, this unified function is called within the setInterval method, which not only simplifies the code but also guarantees that both the data and the DOM elements are updated in sync every second.

2024-05-01 15:11 UTC, RDjarbeng commented
Looks good. Slight revision can you use arrow functions instead to keep all the functions consistent.

2024-05-01 15:13 UTC, RDjarbeng requested changes
Can you use arrow functions for updateDate and setDomElements.

2024-05-02 05:14 UTC, JohnPatrickAncajas commented
> Can you use arrow functions for updateDate and setDomElements.

Yes sir, I'm on it

2024-05-05 00:19 UTC, RDjarbeng approved these changes

2024-05-05 00:21 UTC, RDjarbeng commented
Fixes #126

2024-05-05 00:38 UTC, RDjarbeng commented
Looks good. Go for merge

2024-05-05 00:38 UTC, merged